### ISSUE TITLE
EPUB Table of Contents links to the wrong chapter

### ISSUE THREAD

**Issue by blastdragon** [knighty/fimfiction-issues#110]
I love the new EPUB's. The cover art is on the front page of the EPUB, the synopsis is included in the book and the new table of contents. 
But the table of contents doesn't work right. When clicking on the link for chapter 1 it brings you to chapter 2. Every chapter-link brings you 1 chapter too far into the story. The last chapter-link of a story didn't work on Ibooks (Apple's E-reader app) and on a Kobo E-reader. In Calibre (an e-book management program) it gave a error message.

**Comment by knighty** [comment]
Fixed, and thanks.
