### ISSUE TITLE
Notifications page does not automatically mark as read non-message notifications.

### ISSUE THREAD

**Issue by TrickQuestion** [knighty/fimfiction-issues#114]
I thought this was fixed, but maybe it's intentional. The notification page no longer automatically marks as read non-message notifications. Previously, visiting the notification page would mark all non-message notifications as read (since you've seen them and there's no message to view). This includes bookshelf adds, watches, group join requests, etc. (Although, it never worked for the group join requests. Those always had to be manually marked even if you visited the group.)

**Comment by knighty** [comment]
I sorta debated on this and I don't know why I didn't keep the old behaviour now. I'll change that. If I'm honest I probably just forgot since it was helpful having them stay unread for testing...

**Comment by TrickQuestion** [comment]
Make sure it works for atypical notifications like group requests. Or maybe require them to click on the group, but something should turn it off (previously those were marked unread forever unless you did the "mark all" from the drop-down).

**Comment by knighty** [comment]
This is now changed. Group invites, favourites and follows all get marked read on page view.
