### ISSUE TITLE
Option to disable chapter controls for your story.

### ISSUE THREAD

**Issue by TrickQuestion** [knighty/fimfiction-issues#115]
Feature request: option to disable chapter controls for stories you own. This would permit situations where it is intended that the user _not_ read the chapters in sequential order. Example use cases which already exist on Fimfiction include some anthology stories, stories where each chapter is a different version of the story, and choose-your-own-adventure stories (especially the last one).

**Comment by ssokolow** [comment]
This sort of "force users to..." tends to backfire for two reasons:

1. Users tend to resist when an author tries to force them to read in a way they don't agree with (and possibly declare the site to be "going downhill" for allowing it).
2. There are a *lot* of authors who aren't as smart as they think they are. (See [Dunning-Kruger Effect](https://en.wikipedia.org/wiki/Dunning%E2%80%93Kruger_effect) and the demise of MySpace.)

For a choose-your-own-adventure story, it makes sense... but it's your job to provide clear "make a choice" links anyway. If users still can't understand it, it's their own fault. (I still have a huge collection of print choose-your-own-adventure books from my childhood. If child me could grasp the concept, modern readers don't need to be wrapped in cotton wool to get it.)

Heck, sometimes, I'd flip through linearly, just to see if there were any interesting-looking branches I hadn't yet found my way to.

For the other types, I'm going to read them linearly, whether you want me to or not... just as I do with the short story anthologies I have in print on my bookshelf.

It's just a question of whether I build a habit of reading them like this:

1. Click the first chapter link
2. Curse at the lack of a controls widget
3. Click "Back"
4. Middle-click all chapters in rapid succession
5. Switch tabs and start reading
6. Use <kbd>Ctrl</kbd>+<kbd>W</kbd> to advance chapters

**Comment by knighty** [comment]
Gonna agree with the above.

**Comment by TrickQuestion** [comment]
Though this is closed, you're missing something relative to CYOA. There already exist methods to make it impossible for somepony to click on chapters from the main page, so the argument that "somepony could just click all the chapters" isn't true at all. The chapter controls are the only weakness.

I have a CYOA I've been working on that I have to put padding between early chapters to discourage readers from reading the thing out of sequence, because I actually want it to be a puzzle they have to solve if they want to see the ending. This is enough of a deal that I've considered moving my CYOA work to another site capable of supporting it better.

EDIT: Though it may be better just to call it 'CYOA mode' and have it remove the ability to click on other chapters as well so no gimmick needs to be used. But the gimmick does exist (fortunately).

**Comment by ssokolow** [comment]
Putting it elsewhere may be the best choice. There's only so much a site should do to accommodate an art form with a wildly divergent structure at the possible expense of its primary purpose.

That said, trust me. No matter what you do, people will find a way around it if they want to. For example, choosing to download the entire story as single-page HTML, then using Ctrl+F to search for something common in text but absent in your padding to skip past it. (eg. an article like "a" or "the")

**Comment by TrickQuestion** [comment]
The main reason I asked is it seems like a simple-enough enhancement, and there are many CYOA stories on Fimfiction already. I don't think it's divergent.

That said, you're correct that you can't prevent ponies from doing it absolutely.

**Comment by ssokolow** [comment]
Divergent in structure. Every other form of fiction I've seen has no problem being read linearly, if the reader so chooses. (Anthologies? Sure. Variations on the same story? If you're sure it won't wear on you.)

The problem is that CYOA is a very tiny slice of fimfic's content, compared to "authors who lack the wisdom to only use said feature where it's appropriate". (Hence my mention of MySpace.)
