### ISSUE TITLE
Download BBCode for stories.

### ISSUE THREAD

**Issue by TrickQuestion** [knighty/fimfiction-issues#116]
Feature request: add "BBCode-marked text" to the list of methods for downloading a story. This would be much easier than copy-pasting a chapter (and certainly the entire story) in order to get a BBCode-compatible version.

If there's a simple way to do this with html or epub of which I'm unaware, then nevermind.

**Comment by knighty** [comment]
Is there any use case for this though? It's exposed through the currently-in-the-works API but I'm not sure there's much of a use case for users?

**Comment by TrickQuestion** [comment]
I've needed to do it many times. The most common use case is wanting to pull out a BBCode copy into a text editor like Notepad++ so you can perform search and replace or make other modifications offline (without needing to resort to Google Drive). I have a story I'm updating to fix things and it's a huge pain in the ass that I can't simply download a BBCode for each chapter I need to modify and update. (I gave up halfway through my edits and left it on the to-do pile for months.)

Another use case I've had is moving chapters from one unpublished story to another.

**Comment by knighty** [comment]
I don't really understand why you can't just open the chapter up, grab the bbcode and be done? When you're saving you have to go into each chapter anyway, in what way does this save any measurable amount of time that warrants an extra button?

**Comment by TrickQuestion** [comment]
You have a good point. I can't think of a use case where you'd want to let somepony other than the author download the BBCode, and it's not super-difficult to do manually. I withdraw the request.
