### ISSUE TITLE
RSS or Atom feeds

### ISSUE THREAD

**Issue by cburschka** [knighty/fimfiction-issues#119]
It would be awesome if we could subscribe to updates via an external reader. Public URLs for stories and user blogs/groups would be especially great; a private URL for the user-specific feed might be cool as well.

**Comment by knighty** [comment]
RSS feeds aren't very useful for a dynamic site like Fimfic as they are expensive to operate due to polling, especially with naughty clients. We'll be looking at push notifications soon which are a much more elegant solution.

**Comment by cburschka** [comment]
Hi, I understand if you don't want to add this, but I have to argue that these aren't strong reasons against. Firstly, it shouldn't take any more server resources to respond to a feed request than a normal one (in fact, you can cache public feeds statically and just have the CDN deliver them, as they don't depend on user context the way a full page does). Secondly, even if you generate them dynamically, you can control the polling frequency for well-behaved clients (`Expires` header), save bandwidth using `Last-modified`, `Etag` and HTTP-304 headers, or just flood-limit clients that cause problems.

I don't agree that push notifications (for mobile devices, I assume?) really fill the same use-case. Feeds are a widely used technology supported by many different clients and web applications. To give a personal example, I'm currently using a combination of https://getpocket.com/ and https://feedhuddler.com/ to sync articles onto an e-reader, as well as Thunderbird and a feed reader app in Android. These are all components that work with any website that provides feeds, without requiring a dedicated application for each.

In any case, thanks very much for what you do! :)
