### ISSUE TITLE
Marking a story, or a chapter as 'read,' should increase the views count.

### ISSUE THREAD

**Issue by Huk256** [knighty/fimfiction-issues#126]
Some people (probably a lot) downloads the stories to their e-book readers, read it there, and then marks the stories as 'read' inside Fimfiction library. However, as far as I can tell - **this does not increase the views counter on the story**; in order to do that, we are currently forced to open each chapter, scroll down to the end, and wait for a few minutes, until the algorithm kicks in.

Please consider making a change so that marking the story/chapter as 'read' automatically increment the views counter, and we are not forced to do the tedious: **'find the story we just read on our e-book, open each chapter on Fimfiction, scroll down and then wait for 90 seconds, so that the author can get a much deserved view counter increase'** operation.

**Comment by knighty** [comment]
Now does

**Comment by Huk256** [comment]
@knighty:

Hmm, I just tried it on a few stories, and I don't see any change in the view counter after reload... Is there some timeout for the increase to be noticeable, or should the view counter increase immediately after I mark the story as read and reload the page? 

Or perhaps the change wasn't published yet?
