### ISSUE TITLE
Cheerilee's Tag is Misspelled

### ISSUE THREAD

**Issue by Exuno** [knighty/fimfiction-issues#13]
Most of the tags addressing Cheerilee address her name as "Cherilee". The underlying data-tag and the tag-page itself are about the only place it's correct.

![image](https://user-images.githubusercontent.com/27643668/26869622-0a187c06-4b3b-11e7-86f1-6c7d086a8400.png)
![image](https://user-images.githubusercontent.com/27643668/26869639-18c82e90-4b3b-11e7-86fe-631f0dcd1784.png)
![image](https://user-images.githubusercontent.com/27643668/26869703-69afba26-4b3b-11e7-82d8-a051c5e7c93d.png)

(correct) v
![image](https://user-images.githubusercontent.com/27643668/26869664-3d036ad6-4b3b-11e7-97bc-623aca9b2767.png)

**Comment by Ovalcircle** [comment]
It has been misspelled for so long that I started to believe that was the way her name was spelled

**Comment by knighty** [comment]
Fixed
