### ISSUE TITLE
Clicking on Latest Stories on a user page leads to a 404.

### ISSUE THREAD

**Issue by TitaniumDragon** [knighty/fimfiction-issues#14]
For example:

Click on Latest Stories here:

https://www.fimfiction.net/user/97110/Titanium+Dragon

Leads to here:

https://www.fimfiction.net/index.php?view=category&user=97110

Which is a 404.

Confirmed on other user accounts as well ( https://www.fimfiction.net/user/34244/GhostOfHeraclitus -> https://www.fimfiction.net/index.php?view=category&user=34244 )

**Comment by knighty** [comment]
Issue has been fixed.

Deploying soon
