### ISSUE TITLE
The two spaces at the end of a sentence no longer honored

### ISSUE THREAD

**Issue by scifipony** [knighty/fimfiction-issues#145]
The earlier version of the site supported displaying two spaces at the end of a sentence when reading a story.  The current version ignores the number of spaces and displays only one.  Using two spaces at the end of a sentence changes the sense of certain sentence constructions—with a quoted em-dash for example.  Visually, as a long time author, I feel two spaces between sentences also makes the manuscript easier to read, though some typographists disagree.  Please change your code to recognize multiple spaces and place the appropriate &nbsp when the webapp displays a line for reading (except at the end of a displayed line).  To reiterate,  this was the behavior in the previous version.

**Comment by knighty** [comment]
There is no way to do what you're suggesting regarding not doing it at the end of the line. That's a good reason for not allowing this behaviour alone. I'm not interested in supporting double space after period as automatic markup. You can insert manual nbsp; characters if you need to for specific uses.
