### ISSUE TITLE
Suggestion: up/down votes at the end of chapters should be weighted more heavily than on story page.

### ISSUE THREAD

**Issue by ocalhoun6** [knighty/fimfiction-issues#150]
Here's an idea: make the up/down votes submitted at the end of any chapter in a story (invisibly) count more than the up/down votes on the story's front page. 

Votes that are cast (in either direction) without reading the story are most likely to be done on the story's front page, but votes that are cast at the end of a chapter will almost always be cast by someone who has read at least one chapter of the story.

Now, the displayed vote total for the story would still be incremented +1 or -1 for each vote, so the raw numbers of votes could be tallied without any weighting. But let the story's 'heat' rating (and maybe even the green/red bar) reflect the weighted rating, where votes from people who are more likely to have read the story count for more.

You'd probably want to make this a bit of a stealth feature, not making any big announcement about it, in order to help prevent abuse of it. (Maybe even make the end-of-chapter voting buttons invisibly time-sensitive, so that they only begin to count for more after a certain amount of time is spent on the chapter's page.) But done properly, I think it could help with a common complaint, especially among newer authors, about readers who vote on a story without giving it a fair chance.

Don't know if it's worth implementing, though, since you'd probably have to code in a whole new variable, so the site can track the displayed rating and the weighted rating separately.

**Comment by knighty** [comment]
Such a system would be quickly discovered and passed around (especially with a github issue like this) and then you have a group of people with arbitrarily more power.

In short, no.
