### ISSUE TITLE
Quirky behavior with Reading In Progress

### ISSUE THREAD

**Issue by theaccidentalbrony** [knighty/fimfiction-issues#157]
Okay, so I found this when chatting with a few friends about some of the new features on the site.  Honestly, I had never actually seen the "Reading In Progress" feature work (I didn't even know it existed) until one of them brought it up.  In investigating the code, I've figured out pretty easily why this is happening.  Your autoBookmark.wait value is set to 180, and you are multiplying that by 1000 to set the timeout for both the unload event and the DEBOUNCE for the scroll event.  What this means, based on the code for the debounce method you are using, is that every time the user scrolls, the autobookmark timer is reset to 3 minutes.  For those of us who are quick readers, and/or who like to keep the content near the top of the screen, the autosave functionality will never work.  I'd recommend a much shorter interval for debounce, such as 3 seconds instead of three minutes, since you're already only firing this on scroll and all you are attempting to get rid of are additional scroll events as a user adjusts their scroll position.  A debounce of a few seconds seems more than reasonable to me, and will provide the user a much more accurate save position.  I assume the three minute wait for onclose is to account for users opening a story they are not particularly interested in and therefore do not wish to resume; it may be appropriate to initialize both the close and scroll behaviors with the same timeout (although three minutes may be excessive?), and allow the scroll behavior thereafter to only debounce for a minimal period to exclude superfluous scroll events.   Please let me know if you need more information about this issue.

Edit:   

Steps to reproduce:

1) Log into fimfiction.net
2) Click on a story that your account hasn't already read and click the first chapter.
3) Scroll slightly to adjust the content to the top of your screen.
4) Wait thirty seconds, then scroll.
5) Repeat above behavior for five minutes or so.
6) Close the current fimfiction tab and open fimfiction.net in a new tab.

Expected behavior:  Story would appear in the "Continue Reading" pane
Actual behavior: Story does not appear in the "Continue Reading" pane.

**Comment by knighty** [comment]
You're misinterpreting the point of that debounce. There's two timers. That one controls auto bookmarking when you just leave the tab open for ages and forget about it. There's a seperate timer which enables the auto bookmark on close window.

The reason your example probably fails is because you probably didn't scroll far enough or scrolled too far. Auto bookmarking is ignored if you don't scroll at least 1.5x the window height into the story and the bookmark is deleted/moves to next chapter when you hit the end of the story (with some margin)

```javascript
setTimeout(() => {
    window.addEventListener('unload', () => {
        console.log("Placing unload bookmark...");
    }, false);
}, this.settings.autoBookmark.wait * 1000);
document.addEventListener("scroll", fQuery.debounce(() => {
    console.log("Placing idle bookmark...")
}, this.settings.autoBookmark.pauseTime * 1000));
```

That's the code for how it works (with cruft chopped out)

**Comment by theaccidentalbrony** [comment]
Yes, I had located that bit of code.  The problem is, the debounce resets the timer every time you scroll.  I am at work right now, so I can't post it, but check the code for fQuery.debounce.  I breakpointed it.  It definitely resets the timeout value to three minutes on each scroll, which means the bookmark never gets set if you scroll more than once every three minutes.   Based on your commentary, however, it seems that this was your intent?  

Moreover, I did understand that the timer for the close was separate from the scroll debounce.  3 minutes seems like an arbitrarily high value to me.  Generally speaking, doing mysterious things to a user's experience that are out of their control isn't enjoyable.  Perhaps the auto-bookmark enabling and time values could be enabled as a preference setting to provide better clarity?

As a user, I will say that that the current design of the feature very opaque, and would ask you to reconsider.  However, working as intended is not a bug, per se, even if that functionality appears to be quirky to anyone without knowledge of the mechanics behind it.

**Comment by knighty** [comment]
You're still not understanding it.....the debounce timer does not affect the unload bookmarking at all.

The unload bookmarking timer is 30 seconds. The wait timer is 180 seconds. You're wrong about how it fundamentally works.

I don't think the design is opaque at all, I think it works very obviously. Let me recap how it works.

- Once you have been on the page for 30 seconds the unload bookmark functionality is enabled
- When you scroll, the site updates the latest paragraph you have read up to (the only sane way to do it)
- When you close the tab, the unload event fires and the bookmark is created but only if you've read a little way into it (which I think is intuitive and desired) and only if you're not at the end (in which case it either deletes the existing bookmark or moves it to the next chapter, like Netflix)
- If you leave the window entirely for 3 minutes (or just don't scroll) it sets a bookmark which covers the case where you leave your computer and want to pick up on your phone or whatever later.

**Comment by theaccidentalbrony** [comment]
I understand every single thing you just said.  It is all plainly clear from the code.   

I simply don't understand why the window has to remain untouched for three minutes for the auto bookmark to work.  You seem to have a very specific use case in mind.  I just don't understand why, if you can auto bookmark, you don't simply do it after every scroll ends.  It is not obvious to the end user what you are doing at all.  Again, I was able to figure everything out from the code.  But there is no other way to know how this feature works.  I'm not sure why our communication is failing here.  I am absolutely clear of the following things:

- The site automatically bookmarks your current position in a story after three minutes (180000ms) of no scroll activity

- The site automatically bookmarks your last scroll position if the window is closed after a certain period of time (I'm fairly positive when I checked the autobookmark.wait value it was 180, but I'll take your word for it since I'm not able to check at the moment)

- the site marks a story as read if you have scrolled to the bottom and have the story open for at least 30 seconds.

Again, I am clear on all these bits.  I have been clear on them since investigating the code.  The problem is, this is simply not intuitive for the user.  We spent half an hour last night trying to suss out how to trigger the auto bookmark functionality before I gave up and delved into the code.

**Comment by knighty** [comment]
If you understand it then I don't understand what you're requesting. Do you want the site to constantly spam requests to the server? I truly don't understand what your problem is. Why would it need to bookmark when you haven't even closed the tab or left it? To use a real world analogy, when you're reading a book do you move your bookmark every time you turn a page? No, you do it when you put the book down to read later.

I'm closing this because I think it works fine and as you'd expect.

**Comment by SkyCharger001** [comment]
Just my two cents: but what about browser crash?  (real life comparison: **forced** to drop the book you were reading.) It's something that many developers don't take into account at all.
