### ISSUE TITLE
Odd bbcode to HTML output

### ISSUE THREAD

**Issue by daniel-j** [knighty/fimfiction-issues#16]
[Chapter that generates invalid HTML](https://www.fimfiction.net/story/5170/11/project-sunflower/chapter-10-party-time)

This chapter starts with `<p><p>`, and there's `</p></div></p>` at the end of a center block.

**Comment by daniel-j** [comment]
How to replicate: `[i][center]centered[/center][/i]`

**Comment by xaquseg** [comment]
Fixed, was caused by inline formatting between a line/paragraph break and a block start/end tag.

**Comment by daniel-j** [comment]
Not quite there yet.
![screenshot_2017-06-07_15-49-57](https://user-images.githubusercontent.com/1264014/26882029-77fdd7bc-4b99-11e7-8859-fc5256d90a76.png)

bbcode:
```
[i][center]centered glitch[/center][/i]

[b][right]right glitch[/right][center]some centering [/center] [/b]
```

**Comment by xaquseg** [comment]
Forgot to reopen this, but this edge-case should also be fixed, it was caused by a block element having whitespace after and before it, and the whitespace before it having a block before it.

**Comment by daniel-j** [comment]
Looks good! Nice work!

**Comment by daniel-j** [comment]
It appeared again in another story! :(
https://www.fimfiction.net/story/290208/276/utaan/look-and-find-the-bridge
![screenshot_2017-06-12_17-47-15](https://user-images.githubusercontent.com/1264014/27042451-4a15d924-4f97-11e7-93d2-efc7ada8214f.png)

**Comment by daniel-j** [comment]
This chapter is even worse!
https://www.fimfiction.net/story/290208/186/utaan/the-fire-in-your-eyes
![screenshot from 2017-06-12 17-54-34](https://user-images.githubusercontent.com/1264014/27042765-429b81b6-4f98-11e7-8066-13c222ae2bc2.png)

**Comment by xaquseg** [comment]
Inline formatting breaks if it's on its own line and there are blocks around.

**Comment by xaquseg** [comment]
Fix deployed.
