### ISSUE TITLE
Most user profile modules are not visible on mobile

### ISSUE THREAD

**Issue by daniel-j** [knighty/fimfiction-issues#21]
Only the profile comments are shown.
https://www.fimfiction.net/user/189713/djazz

![screenshot_2017-06-07-14-30-53](https://user-images.githubusercontent.com/1264014/26878550-306eb6a6-4b8e-11e7-990e-8102b1912fee.jpg)

**Comment by knighty** [comment]
This is intentional. There's no good way of showing the desktop view on mobile. An alternative method may be considered in the future or a button on the page to specifically drop into desktop mode for user pages, but currently this is intended and won't be changed any time soon.
