### ISSUE TITLE
API sees two tags that are not usable from the site UI

### ISSUE THREAD

**Issue by Lithl** [knighty/fimfiction-issues#212]
GET /api/v2/story-tags

Two of the tags in the result set are:

    {
        "id": "4",
        "type": "story_tag",
        "attributes": {
            "name": "My Little Pony: Friendship is Magic",
            "type": "series",
            "description": "My Little Pony Friendship is Magic is an animated series based on Hasbro's popular My Little Pony franchise. The show premiered on October 10, 2010 on Hasbro's The Hub channel, and has currently ended its fourth season. This incarnation of the franchise is referred to as the fourth generation, or G4, of My Little Pony. The show was developed for television by Lauren Faust, who is known for her work on two of Cartoon Network's popular and critically-acclaimed franchises, The Powerpuff Girls and Foster's Home for Imaginary Friends.\r\n\r\nThe series stars a unicorn pony named Twilight Sparkle, a student of Princess Celestia, the ruler of the magical land of Equestria. The princess gives Twilight the task of learning about friendship and sends her and her assistant, a baby dragon named Spike, to Ponyville. There, they meet some interesting ponies, including action-loving Rainbow Dash, glamorous Rarity, hard-working Applejack, timid Fluttershy, and hyperactive Pinkie Pie. Together, they go on adventures, solve various problems, and learn about the magic of friendship."
        },
        "meta": {
            "old_id": "",
            "url": "https://www.fimfiction.net/tag/mlp-fim"
        }
    },

    {
        "id": "124",
        "type": "story_tag",
        "attributes": {
            "name": "Fallout Equestria",
            "type": "universe",
            "description": "Fallout: Equestria is a crossover fan-fiction between the My Little Pony: Friendship is Magic television series and the Fallout video game series, and was written by Kkat. First published in April 2011 and completed on Christmas of that year, Fallout: Equestria spans 45 chapters (as well as a prologue, introduction, epilogue, and afterword), and contains over 620,000 words, making Fallout: Equestria one of the longest self-published works of derivative fiction in existence."
        },
        "meta": {
            "old_id": "",
            "url": "https://www.fimfiction.net/tag/fallout-equestria"
        }
    },

Neither tag is accessible from the site's story editing UI, nor are any stories using these tags.

**Comment by xaquseg** [comment]
These tags are of a type not currently used by the site, I'm not sure if we want to keep exposing them via the API or if we want to filter them out until this type is used.

**Comment by Lithl** [comment]
With the recent tagging update, tag 4 above is now available from the site UI, and tag 124 above has been removed from the API result. (Series tag "Fallout" with id 311 now exists.) Closing resolved issue.
