### ISSUE TITLE
Bring back preview button for blog posts. Please please please.

### ISSUE THREAD

**Issue by TrickQuestion** [knighty/fimfiction-issues#218]
n/t

**Comment by baxil** [comment]
The Preview button has moved to someplace unintuitive, but it's still there.

Check the row of icons above the blog window.  One of them is an open eye.  Clicking that will overlay a post preview on top of the editing area.

I do think that, from a UI perspective, the old "Preview" button was much better placed — currently it's buried in with the formatting options, and it's counterintuitive to have Preview/Fullscreen/Settings be the only non-formatting options in a formatting bar.
