### ISSUE TITLE
Nested [i] doesn't output as expected

### ISSUE THREAD

**Issue by daniel-j** [knighty/fimfiction-issues#22]
`[i]This should be italic. [i]Still italic.[/i] [b]Italic and bold[/b][/i]`
Output before update: _This should be italic._ _Still italic._ **_Italic and bold_**
Output after update: _This should be italic._ _Still italic._ **Italic and bold**

**Comment by knighty** [comment]
Intentional behaviour. The tags aren't nested. The [/i] effectively acts as "turn italics off"
