### ISSUE TITLE
Refresh button in the feed doesn't work.

### ISSUE THREAD

**Issue by HuttBurt** [knighty/fimfiction-issues#220]
What it says on the title. I press refresh and nothing happens whether there are new things to refresh or not. I have to re-enter the feed to refresh.

**Comment by Sollace** [comment]
Confirmed. Clicking refresh results in the following error being printed to the console:

> c is undefined

Relevent code and fix would be:

```js
FeedController.prototype.loadNewerFeed = function(c) {
  if (this.loading) return;
  this.loading = true;
  new AjaxRequest({
    url: '/ajax/feed',
    method: 'GET',
    button: c,
    spinner: c.querySelector('i'),
    data: { min_date: this.getFirstTimestamp(), feed_view: this.viewMode },
    success: c => {
      this.loading = false;
      c.items.reverse().forEach(e => {
        this.addItem(c.items[e], true); //
      });
    }
  })
};
```

Replace `c.items[e]` with just `e` and it works.

**Comment by xaquseg** [comment]
Should be fixed.
