### ISSUE TITLE
Chapter controls obscure paragraph controls for the first paragraph

### ISSUE THREAD

**Issue by Tropony** [knighty/fimfiction-issues#240]
When a chapter title is long compared to the reading line width, the "previous-chapters-next" controls will float down below the title line. Then, if you select the first paragraph, the "read-bookmark-quote" controls will show _behind_ the floating chapter controls, resulting in it being impossible to start text-to-speech for that paragraph.

![Screenshot showing this effect](https://user-images.githubusercontent.com/33595092/32698027-325ed0b4-c79d-11e7-8c7a-f1ecf3e7d4c8.png)

Firefox 56, Windows 10 64-bit.
Also seen with Chrome 62.

**Comment by knighty** [comment]
This shouldn't be an issue anymore

**Comment by Tropony** [comment]
Agree that this is fixed. The nav buttons now stay in place and instead the chapter title wraps.
