### ISSUE TITLE
Ezn's fanfic/writing guide is now hosted on a different site

### ISSUE THREAD

**Issue by DanielOaks** [knighty/fimfiction-issues#242]
Heyo! On the [new story page](https://www.fimfiction.net/manage/stories/new), there's a link to Ezn's writing guide.

The page currently sends people to http://eznguide.rogerdodger.me/ (which is a dead link these days). It looks like the guide is now hosted at https://eznguide.neocities.org/

**Comment by knighty** [comment]
This is fixed now
