### ISSUE TITLE
Legacy support for track.fimfiction.net

### ISSUE THREAD

**Issue by cburschka** [knighty/fimfiction-issues#244]
For some time, notification emails sent by Fimfiction routed inbound links through a click-tracker, at track.fimfiction.net.

Unfortunately, because that domain is now gone all links from old emails are broken. (I'm not the only one who obsessively archives mail and refers back to it, right? :P )

Fortunately, the old links contain the actual URL (though in twice-json-encoded, then base64-encoded form), so all that's required is a one-line script served at track.fimfiction.net.

Sample URL (w/ linebreaks):
```
http://track.fimfiction.net/track/click/30290722/www.fimfiction.net?p=
eyJzIjoiV1VudWk3Nm5BRDB1TVVnLTY3bGRSZXgyQ1E0IiwidiI6MSwicC
I6IntcInVcIjozMDI5MDcyMixcInZcIjoxLFwidXJsXCI6XCJodHRwOlxc
XC9cXFwvd3d3LmZpbWZpY3Rpb24ubmV0XFxcL3N0b3J5XFxcLzIxNTEwXF
xcL2ZvcndhcmQjY29tbWVudFxcXC81OTMxOTg2XCIsXCJpZFwiOlwiMjlj
NWI3NGVmOTc3NGY0MmJjODg0ODdlZGE1MmMxZTZcIixcInVybF9pZHNcIj
pbXCJkY2VhNTg2ZDdmZTA1ZGRmMTFjYmZkZmQ2ZDUyYTFhMDMwNWYyZTIw
XCJdfSJ9
```

I'm locally using something like this (with a hosts file entry for track.fimfiction.net), but that isn't really a solution on mobile:

```php
    header('Location: ' . json_decode(json_decode(base64_decode($_GET['p']))->p)->url, 302);
```

It would be neat if that redirect was provided again. :)

**Comment by knighty** [comment]
I appreciate this is an annoying issue but It's not something I'm particularly interesting in doing a fix for.
