### ISSUE TITLE
Possible database issue with user 'Random Bits'

### ISSUE THREAD

**Issue by badhorsey** [knighty/fimfiction-issues#245]
I got notifications of comments on posts from user 'Random Bits'.
When I looked, the comments weren't there, nor was there a notice of a deleted comment.
Trying user's [user page](https://www.fimfiction.net/user/316086/Random+Bits) gives an http error 500: Internal server error
The site statistics page says there are only about 235,000 registered users, so that user ID of 316086 is probably too high.

**Comment by knighty** [comment]
https://www.fimfiction.net/user/318125/Random+Bits
