### ISSUE TITLE
Video ad force-scrolling to the bottom of the page

### ISSUE THREAD

**Issue by yosup7400** [knighty/fimfiction-issues#249]
I read fimfiction on the mobile version of chrome on my LG tablet. I frequently experience video ads forcefully scrolling the page down so that they are in the center of my view. These ads do this every second until the ad has finished playing. I must manually scroll back up to find my place, but these ads occur every five minutes or so, making reading long chapters immensely frustrating.

**Comment by knighty** [comment]
I can't do much about these, you can try reporting them to google if they continue to be an issue
