### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by AdBarrThree** [knighty/fimfiction-issues#253]
Hey, new to git hub, I use the edge browser of windows phone 8 and for some reason the login button on Fimfiction.net is not working properly. This may or may not be related to the fact that I own two accounts, one being Summertime and the other being PonyMadness, and I may have had the "Remember me" tab selected on both for this device. Whatever the case, I cannot log in with either account. Please help.

**Comment by AdBarrThree** [comment]
Also, I may add that I don't have this issue on PC, it is specific to mobile

**Comment by NumeronEight** [comment]
Have you tried [clearing the cookies](https://privacy.microsoft.com/en-us/windows-10-microsoft-edge-and-privacy) of Edge on your smartphone?

If that didn’t help, could you please give us some other details about your issue?  The specific error message you’re receiving could be rather useful, or, alternatively, what does happen and how does that differ from what you expect to have happened? Which steps are you taking to get that to happen? You can be as detailed as you like, anything could be useful.

On a side note, I couldn’t find a list of supported browsers for FimFiction, so I can’t say for certain that Edge on Windows Phone 8 is supposed to be supported, if anyone could point me in the right direction they would be welcome.

**Comment by AdBarrThree** [comment]
Well... it turns out on windows phone, one must clear their history in order to the clear the cookies. I did so and I no longer have the problem. Thank you for responding so soon, I appreciate it.
