### ISSUE TITLE
Bottom 3 stories in the feature box are not displaying tags

### ISSUE THREAD

**Issue by ocalhoun6** [knighty/fimfiction-issues#260]
[A story in the top portion of the feature box](https://image.prntscr.com/image/dbEaaUnTQS23BOF2c50qqg.png)

[A story in the bottom portion of the feature box](https://image.prntscr.com/image/Q6a6kn__SUWsfjVg6TtmDQ.png)

I've checked, and the latter story *does* have tags assigned, but they're not displaying. All the stories in the chapter update section of the feature box are missing their tags when displayed.

**Comment by ocalhoun6** [comment]
Also, on further looking, tags are not displaying in the 'popular stories' box, either. Although this part may be intentional, due to the limited space.

**Comment by knighty** [comment]
This is fixed now.

Edit: Also they're intentionally not shown in popular stories, but it's not something I'm on the fence about
