### ISSUE TITLE
Noncon tag should apply to nonsexual situations, too.

### ISSUE THREAD

**Issue by TrickQuestion** [knighty/fimfiction-issues#264]
Currently the definition of the Noncon tag makes no sense absent the Sex tag, but there are plenty of Noncon triggers worth warning an audience about that aren't sexual in nature:

* Discord's mind rape
* Ponies being tied up and tormented
* Blackmail

Those even end up on the show. I'd like the Noncon tag's definition to be any situation where a pony is forced to do something entirely against their will. It would be more useful with that definition and there would be no ambiguity since the absence of the Sex tag would indicate clearly.

**Comment by knighty** [comment]
I don't think those are things that belong in the current definition of what we have for non-con. I don't think any of them really warrant a "warning" exactly. When we have further tagging those things will probably be better covered there.
