### ISSUE TITLE
Rating a story from inside a chapter

### ISSUE THREAD

**Issue by Xonxt** [knighty/fimfiction-issues#270]
Here's what it looks like
https://clip2net.com/clip/m73955/e85bd-clip-15kb.png

Seems to be only happening for stories consisting of only one chapter, and only when you're currently viewing said chapter. Doesn't happen for every story though, only a small amount.
When you go back to the story description and list of chapters, the issue is gone.

My browser is Opera 49.0.2725.64, but the same seems to happen on other browsers (I also checked on the Android version of Chrome 63.0.3239.111)

**Comment by knighty** [comment]
This is fixed now. Issue was to do with the heat icon.
