### ISSUE TITLE
Dropdown menus aren’t vertically aigned on mobile

### ISSUE THREAD

**Issue by bit-13** [knighty/fimfiction-issues#274]
On mobile, the dropdown menus for notifications and PMs don’t appear directly under their icons. They actually appear just below the visible area onscreen; ie if I scroll down I see the menu floating in the middle of the page contents. I observed this on two different iOS devices today, after trying night mode for the first time in mobile.

**Comment by bit-13** [comment]
And this morning the menus are fine again on both devices....

**Comment by knighty** [comment]
Yeah I fixed this earlier
