### ISSUE TITLE
Blog pane on user pages no longer shows first image of blog (animated or otherwise).

### ISSUE THREAD

**Issue by TrickQuestion** [knighty/fimfiction-issues#3]
Unsure if this was intentional; hoping it wasn't.

**Comment by knighty** [comment]
It was intentional because it was a problem with large images.

**Comment by TrickQuestion** [comment]
Okay! The intent seems odd, though. It's only three* thumbnails at most, and viewing a user's blog proper doesn't hide any of the images (at full size).

(* Related, the blog bar on my user page (non-mobile) won't show more that three posts, even though it's set to show five. It might be limited to a short maximum height in the side-frame? I don't mind, but that's where that number is from.)
