### ISSUE TITLE
"Reading" tab on mobile doesn't include pre-4.0 incomplete stories from your library.

### ISSUE THREAD

**Issue by TrickQuestion** [knighty/fimfiction-issues#31]
Seems like it should be possible to update the "Reading" tab to include incomplete stories in your library from pre-4.0, since the site still easily identifies those stories.

Also, there's no Reading tab or functionality on nonmobile (that I can find).

**Comment by xaquseg** [comment]
Reading tab is based on mid-chapter positions and tracks stuff you're actively reading, it does not replace the related bookshelf unread tracking functionality.

Non-mobile reading is on the top-right of the homepage.

**Comment by TrickQuestion** [comment]
Ah. I must not be seeing it because I'm not reading anything at the moment! :derpytongue2: Thanks.
