### ISSUE TITLE
Please delete this i messed up

### ISSUE THREAD

**Issue by Ovalcircle** [knighty/fimfiction-issues#32]
Can someone delete this? I messed up, and i don't want an unfinished description with no pictures

**Comment by Ovalcircle** [comment]
I found out how to close it myself

**Comment by FM-96** [comment]
Why didn't you just edit the description to add the pictures? o_O

**Comment by Ovalcircle** [comment]
I had no mobile pictures, so I had to screenshot it, email myself, and then put that in the message. I was afraid that you would look at this issue within those few minutes and not see the mobile pictures, so I just made a new one.
