### ISSUE TITLE
Login not working on desktop again

### ISSUE THREAD

**Issue by SplashSurfer216** [knighty/fimfiction-issues#320]
Once again, the same problem I've had about 2 months ago is happening again. I recently update my Nextbook and it signed me out of Fimfiction, so now when I try to log back in, it keeps loading again and I once again get the access denied symbol on my cursor. Can you figure this out again? I have story chapters to reupload after a retooling and I have to have a few chapters of mine critiqued by a partner, and I'd really appreciate this getting straightened out.

Update: Still no progress, not to be rude but what's the hold up? I get you have a lot of issues to work out, but I got a good response last time! What's going on?

**Comment by mxdanger** [comment]
Stop reposting the same issue as you are not giving any useful information. Try clearing the cashe and cookies on your browser.

**Comment by SplashSurfer216** [comment]
Okay, there's no need for rudeness, I'll try it.
