### ISSUE TITLE
Add the Also Liked/Similar/Author tabs to mobile. Pictures inside

### ISSUE THREAD

**Issue by Ovalcircle** [knighty/fimfiction-issues#33]
Desktop is first picture. Mobile is second and third. The story was randomly picked,  I'm not advertising it.
The pullout page is gone from mobile and that's what the picture are trying to show. Also, ignore the tab format, I zoomed out.
![fimfiction issue 4 0 story](https://user-images.githubusercontent.com/29266457/26908442-b10ad148-4bc8-11e7-84e0-cb118f012b2a.PNG)
![fimfiction issue 4 0 story mobile 1](https://user-images.githubusercontent.com/29266457/26908444-b38d0ddc-4bc8-11e7-8a07-f1e1dcf006f5.PNG)
![fimfiction issue 4 0 story mobile 2](https://user-images.githubusercontent.com/29266457/26908445-b394e246-4bc8-11e7-925a-26abf7f37a0b.PNG)

**Comment by knighty** [comment]
This is now done.

**Comment by Ovalcircle** [comment]
Thank you.
