### ISSUE TITLE
Editing things don't work still.

### ISSUE THREAD

**Issue by TheMajorTechie** [knighty/fimfiction-issues#35]
Editing comments, blogs, etc. is still broken, and appears to give a blank strip of nothingness rather than the editing box.

**Comment by Nyerguds** [comment]
Strange. This only happened to me when I had no connection to the internet.

**Comment by knighty** [comment]
Can you screencap?

**Comment by TheMajorTechie** [comment]
I'm on my phone right now, but I believe the problem is the same on mobile. I'll send a scfeencap of that instead.

**Comment by TheMajorTechie** [comment]
... Oh. It works now. Never mind. Yesterday I wasn't able to wait comments or blogs though.
