### ISSUE TITLE
Embedded in-text images not displaying

### ISSUE THREAD

**Issue by midnightwolfGX** [knighty/fimfiction-issues#357]
Recently, some images I have embedded in my stories (under my same username as on this site) have stopped displaying. These images are under fair use with permission from the artists, and not being used for commercial gain of any type. I have attempted to use different URLs for different scaling of the images, but so far, nothing has worked to resolve this issue.

The website I post the images to is Flickr.com, and when I load the URL of the images into the search bar, it displays properly with no issue.

I am not aware of how many users this issue is affecting, but if it can be resolved, it would be most appreciated.

**Comment by SomewhatDamaged** [comment]
A little more info would be great.

Linking the images on here would be a good start, as without them it's a little hard to test this.

**Comment by midnightwolfGX** [comment]
Of course. Here are some URLs from my fic, _Your Loyal Subject_, that have stopped displaying. They appear for a few hours before the bug occurs:

https://live.staticflickr.com/1842/44562544991_58ba5f2eee_b.jpg

https://live.staticflickr.com/65535/47925620292_a21a06491d_h.jpg

**Comment by SomewhatDamaged** [comment]
At a guess I'd say flickr has blocked fimfic's proxy, which means they won't be usable as an image host.

I'd suggest either an S3 bucket, or perhaps using google photos and linking directly to the image.

**Comment by midnightwolfGX** [comment]
Okay. I will try that. Thanks for the tip.
