### ISSUE TITLE
Returning from fullscreen comment box doesn't adjust icons

### ISSUE THREAD

**Issue by Nyerguds** [knighty/fimfiction-issues#39]
If you set the comment editor to full screen and then switch back to small view, and the window is too small to show all icons, they still all get displayed, instead of adjusting to the reduced size.

![image](https://user-images.githubusercontent.com/1840281/26917624-49c30052-4c2f-11e7-8aca-2a09eae5a76b.png)

This problem does not seem to occur if the window is narrow enough to switch to mobile layout.

**Comment by knighty** [comment]
Should be fixed
