### ISSUE TITLE
(Minor) Reply chain symbol/syntax is somewhat confusing.

### ISSUE THREAD

**Issue by TrickQuestion** [knighty/fimfiction-issues#4]
The curved arrow symbol and new syntax is a little confusing. In messages, it looks like clicking it will actually create a reply; in the header, it looks like the user is pointing at the downhoof symbol. In both cases it doesn't look like a link (it is the same color as the text). I also keep forgetting which one is which because they look identical (even though it should be obvious, so that might be me).

**Comment by knighty** [comment]
I don't really think it particularly an issue, just a minor preference thing.
