### ISSUE TITLE
Links in sidebar on mobile appear to be offset

### ISSUE THREAD

**Issue by FM-96** [knighty/fimfiction-issues#40]
Long pressing on any of the buttons in the sidebar in mobile Chrome reveals that the actual link seems to be offset from the button.

It still works fine, though, even if you press on the area that seems to be above the link, so I think this is only a cosmetic issue.

![screenshot_20170608-042337_8_25](https://user-images.githubusercontent.com/4470619/26921626-f2c0fc2e-4c3c-11e7-9472-be2821664bb7.png)

**Comment by knighty** [comment]
This is a chrome bug that was fixed super recently so you're just on slightly old mobile chrome.
