### ISSUE TITLE
Statistics on footer report 0 hits always

### ISSUE THREAD

**Issue by NumeronEight** [knighty/fimfiction-issues#41]
In any page's footer, statistics show 0 hits today, 0 yesterday. I started noticing it after the fimfiction 4.0 update (June 5th) and it has been always 0 until today (June 8th). I've noticed this on the latest chrome desktop (windows 10) and mobile (android 4.4 smartphone), but I believe it to not be platform dependent.

 Also, the "Site Statistics" link points to a nonexistent page (https://fimfiction.net/statistics , error 404).

![cattura](https://user-images.githubusercontent.com/29285690/26942065-0210b914-4c81-11e7-92d6-e607550e9a31.PNG)

**Comment by NumeronEight** [comment]
Possible duplicate: issue #48

**Comment by knighty** [comment]
Fixed
