### ISSUE TITLE
Comment hotkeys conflict with German keyboard layout

### ISSUE THREAD

**Issue by FM-96** [knighty/fimfiction-issues#44]
I believe I've already seen something similar mentioned on the site's Discord, but seeing as there is no issue about this here yet...

I'm using a German keyboard layout, and a few of the hotkeys for writing comments (and maybe other things; I haven't written anything but comments yet) clash with that.

Specifically:
- AltGr+Q is supposed to type a `@`, but inserts `[quote][/quote]` instead.
- AltGr+E is supposed to type a `€`, but opens the "Add Embed" popup instead.
- AltGr+8 is supposed to type a `[`, but inserts `[list]
[*]
[/list]` instead.

**Comment by knighty** [comment]
This should now be fixed.
