### ISSUE TITLE
Statistics Page Returns 404

### ISSUE THREAD

**Issue by whoofian** [knighty/fimfiction-issues#48]
Title says it all. This may be why the statistics are showing 0 hits across the board; there weren't any hits because the page doesn't exist. This means your stats counter checks for bad input, which is good! I'll continue looking for problems as I use the site.

**Comment by NumeronEight** [comment]
This issue has now been fixed by @knighty, as reported in issue #41, in which both the statistics link and the hit count have been dealt with.

This issue can now be closed.
