### ISSUE TITLE
Comment Section in BBCode Guide reports incorrect date on new comment

### ISSUE THREAD

**Issue by whoofian** [knighty/fimfiction-issues#52]
When I posted a comment on the BBCode page as to why switching to BBCode was great for security, the timestamp of the comment returned 6 days, not "just now." Even if the "just now" feature has been eliminated with this update, that is broken. Screenshot attached. 

![fimfiction comment section bug](https://user-images.githubusercontent.com/29294263/26958672-f9ae0aa6-4c99-11e7-90e2-315d5333f16f.JPG)

**Comment by knighty** [comment]
Time offset can no longer be negative which should fix this.
