### ISSUE TITLE
Clicking on comments moves 'highlight' bar

### ISSUE THREAD

**Issue by bloons3** [knighty/fimfiction-issues#53]
![image](https://user-images.githubusercontent.com/3241376/26962691-a68b55b8-4cad-11e7-80c7-a161dc23aa12.png)

If this is intended -> Highlight bar appears behind comment, clicking speaker icon doesn't read comment out loud
If this is not intended -> clicking on comments moves highlight bar

**Comment by bloons3** [comment]
also quotes people 
![image](https://user-images.githubusercontent.com/3241376/26963055-28ece39e-4cb0-11e7-9bd6-6f81db5b0a1c.png)

**Comment by xaquseg** [comment]
The code that does that stuff is failing to exclude comments. Might also explain a few other bugs we've seen.

**Comment by knighty** [comment]
This is now fixed, thanks.
