### ISSUE TITLE
Link to a Discord account on the About page links back to fimfiction

### ISSUE THREAD

**Issue by ReluctusB** [knighty/fimfiction-issues#58]
On a user's about page, if they have linked a Discord account, the link goes to https://www.fimfiction.net/user/[user_id]/[username]/[discord_account] instead of whatever it is it's supposed to. You can actually use this to link to other pages on fimfic; setting the account to 'stories' and clicking the link will take you to a user's story page.
However, if you start the account with a '#', it links to https://www.fimfiction.net/user/[user_id]/[username]/about#[discord_account].

**Comment by knighty** [comment]
Fixed
