### ISSUE TITLE
Searching Fimfiction by Users Breaks on Second Page

### ISSUE THREAD

**Issue by kristopher-miles** [knighty/fimfiction-issues#60]
When searching users with no term, it is impossible to search past the first page. For example, suppose I wish to view users by number of subscribers. The first page works as expected, as you see below:

![not broken](https://user-images.githubusercontent.com/15851577/27000544-ce0fd75a-4d69-11e7-8d72-f26a18b68854.png)
Then I click the next arrow, or the "2" button on the top of the screen there, instead of going to the second page of users sorted by followers, I go to the second page sorted by registration, the default:

![broken](https://user-images.githubusercontent.com/15851577/27000561-3095d71c-4d6a-11e7-9290-87d1ff726afd.png)

**Comment by knighty** [comment]
Fixed

**Comment by 0joshuaolson1** [comment]
After page 1400 or so, I see the same problem. Although this isn't unique to users - depending on how stories are ranked, the page list [shows up](https://www.fimfiction.net/stories?order=relevance&page=1000) and later pages [break too](https://www.fimfiction.net/stories?order=relevance&page=1001).

Which I just emailed you about today before finding this place. Sorry!
