### ISSUE TITLE
Autolinked URLs should exclude punctuation at the end

### ISSUE THREAD

**Issue by cburschka** [knighty/fimfiction-issues#66]
When putting URLs in text, they're often followed by the characters `,.);` (and possibly other punctuation). Right now, the comment parser will include these in the URL, so you need to add a space after URLs to avoid breaking them.

```
(see https://google.com/, or https://google.com/).
```

turns into

> (see [https://google.com/,](https://google.com/,) or [https://google.com/).](https://google.com/\).)

With a slightly improved regex, this can be avoided, as GitHub does: (see https://google.com/, or https://google.com/).

With some extra code, you can even distinguish between https://en.wikipedia.org/wiki/Title_(disambiguation) and "https://en.wikipedia.org/wiki/Title)". This [C implementation](https://github.com/vmg/redcarpet/blob/master/ext/redcarpet/autolink.c#L100) simply counts from the end to only include balanced pairs of parentheses.

**Comment by xaquseg** [comment]
Handled common punctuation including parentheses (w/detecting balanced pairs). Should handle multiple trailing punctuation properly too.
