### ISSUE TITLE
Error box popping up saying 'undefined'

### ISSUE THREAD

**Issue by GabrielCNoble** [knighty/fimfiction-issues#67]
An error box saying 'undefined' very often pops up when switching between the inbox, feed and notifications tab. It happens more frequently when switching between inbox and notifications. To make it happen, just switch between the two very quickly. There's a image attached to it showing the thing...

![error](https://user-images.githubusercontent.com/16003370/27002873-711a01a2-4dc2-11e7-9d5a-326942692c66.png)

**Comment by knighty** [comment]
Considering a see a custom pony in the top right I'm gonna assume you have some Fimfic extensions which are broken on the update. Try disabling them.

**Comment by GabrielCNoble** [comment]
Disabled, but the box still pops up.

**Comment by knighty** [comment]
Can you try using the site in an incognito/private browsing window and see if it still happens? Also what browser/OS?

**Comment by GabrielCNoble** [comment]
I'm using firefox/win7. I tried on incognito mode and still happened. I also tried on chrome, and it didn't happen there, even with custom scripts enabled.

**Comment by knighty** [comment]
Is it possible you're running a very old copy of Firefox? The fact that the icons aren't loading points to some issues

**Comment by GabrielCNoble** [comment]
Nope, it is up to date. The icons were showing up properly a few days ago if I'm not mistaken.


![error2](https://user-images.githubusercontent.com/16003370/27004737-cc6596a8-4de4-11e7-86f2-b817cc453969.png)

**Comment by TrickQuestion** [comment]
If the extension isn't registered on the list of extensions, I'm not certain disabling would always work.

You should probably try clearing cookies, cycle the browser, then log in and see if it's still a problem.

**Comment by henriquegemignani** [comment]
This also happens with me on Firefox for Android. It appears to be when some sort of network request is cancelled: network status changes (wifi/mobile switches), clicking on a link after trying to thumbs up/down a story.
My mobile firefox has no extension, and I keep it regularly updated. Running Android 6.0, but I do have adway installed (/etc/hosts entries to block ads).

I think this may have happened on my desktop Firefox some time or another, but the frequency is not comparable. But I do access internet via a cable there.

**Comment by GabrielCNoble** [comment]
Still happening.

**Comment by knighty** [comment]
@GabrielCNoble is it fixed now?

**Comment by GabrielCNoble** [comment]
Yup :) What was the cause of it?

**Comment by knighty** [comment]
@henriquegemignani was correct. Issue only manifested in Firefox so I'd never noticed and spent about an hour hunting it down last night :P
