### ISSUE TITLE
BBCode button bar occasionally breaks the layout

### ISSUE THREAD

**Issue by cburschka** [knighty/fimfiction-issues#68]
I'm getting some layout glitches with the editor bar on occasion (not always) on Chrome. Unfortunately I haven't yet found a way to consistently reproduce it, but it might be a problem in calculating the available area, and on the desktop it usually goes away when resizing the window past a breakpoint and back.

![Desktop](http://i.imgur.com/MyMbysQ.png)

I haven't found a way to work around it on mobile; I usually rotate to horizontal mode in order to reach the quote button when it is hidden like in this screenshot:

![Mobile](http://i.imgur.com/Jgw9tOX.png)

(Also, the button order seems to shift around every now and then, which is pretty confusing. That part is unrelated though.)

**Comment by knighty** [comment]
This should be fixed

**Comment by cburschka** [comment]
(Confirmed that it isn't happening anymore on my device.)
