### ISSUE TITLE
Footnote support

### ISSUE THREAD

**Issue by cerebrate** [knighty/fimfiction-issues#71]
For those of us who write in the school of Terry Pratchett and Susanna Clarke, can we have explicit footnote support, or the old option back?

Simply placing them at the bottom of the chapter, separated by [hr], is less than optimal either on the site or in epub, since it forces the reader to scroll - I've had explicit complaints about this - and while it's possible to insert them inline in the text (say, indented and set off using [quote], and reduced in [size]), that's ugly and breaks the flow of the story.

We used to have a good solution to this in the form of the [right_insert] tag, which gave us a boxed insert which could be kept near the footnote reference and which (being boxed and shaded) was obviously not part of the main story text and so didn't break flow.

Could we please have that back again? Or failing that, something like the e-book model with markup which generates a footnote marker that lets the reader - both on-site and in e-pub - scroll to the footnote with one click and then back again with another? Or something, anyway.

**Comment by ssokolow** [comment]
I have to second this. One of the biggest reason I use (or am migrating to) reStructutedText for my non-fiction stuff is that every renderer I've ever encountered ([including GitHub's](https://gist.github.com/ssokolow/2fb8debc7dfdbf1d9a0da90284f5d73a)) agrees that footnotes should have first-class markup support which produces hyperlinks in both directions.

(Thus compensating nicely for the fact that web pages aren't (and shouldn't be) broken into small pages.)
