### ISSUE TITLE
Performance Regressions on Scroll

### ISSUE THREAD

**Issue by stillinbeta** [knighty/fimfiction-issues#72]
I've noticed serious performance issues when scrolling stories on the new fimfiction 4.0 release. 
Here's a screenshot of the Chrome Javascript profiler. Each of those spikes in CPU represents me hitting page up or page down:
![image](https://user-images.githubusercontent.com/523632/27005194-46f9c194-4de7-11e7-8da4-0219c293454a.png)

The Chrome Task Manager also shows spikes of anywhere from 30-40% CPU on my laptop (an older i5 running Linux). 

My partner (a Chrome developer) was able to reproduce on her mid 2014 macbook 13" Macbook Pro running Chrome. She was pretty surprised by the amount of rendering time and Javascript time taking up by scrolling the page: 1 second each for rendering and javascript out of only 8 seconds of capture time.

We've looked at a story in Safari too, and performance is similarly miserable. My partner says it looks from the profiler in Safari like the page is being re-rendered on every scroll, leading to a lot of CPU usage.

This doesn't make the site unusable on any of my laptops, but my tablet (an iPad Mini 2) is a different story. Before the 4.0 update I had to deal with the occassional tab crash, but now even scrolling sometimes lags for seconds at a time, and anecdotally I think crashes on iPad are a lot more frequent.

I've attached a log of one of my profile runs, which should be loadable into Chrome. I'm happy to provide any other debugging information you'd find helpful! I'm an engineer as you may have suspected, but front-end is very far from my area of expertise.

[profile.zip](https://github.com/knighty/fimfiction-issues/files/1066029/profile.zip)

**Comment by knighty** [comment]
What page are you on that's causing this? We only have one scroll handler really and I'm surprised if it's causing that, but I'm looking into it.

edit: Checked myself and I'm seeing nothing odd. The function we use for lazy loading images throttles at 10 runs per second and executes in about 0.2ms for me. I'm not seeing anything like you are. It could be ads I'm afraid >:

**Comment by knighty** [comment]
I'm gonna close this for now. @stillinbeta If you discover anything I'd like to know.

**Comment by stillinbeta** [comment]
I was gonna see if I could figure out how to block the ads temporarily to see if that was the issue, but lo and behold now there's a patreon I can back to get rid of 'em. I'll test that out for a few days and see if it improves things.
