### ISSUE TITLE
Unread Chapter Counter

### ISSUE THREAD

**Issue by FloydienSlip** [knighty/fimfiction-issues#8]
On the Library icon in the main user toolbar (with Settings and Groups and so on), the unread chapter counter does not update after visiting an unread chapter's page. For example, if a new chapter of a story I'm tracking came out, clicking the chapter's page does not update the counter to (0) and instead it remains at (1). Refreshing on the chapter page solves the issue.

**Comment by knighty** [comment]
Chapters don't mark read until you're 60% of the way through and have been on the page for at least 30 seconds. Means this problem can't go away I'm afraid.
