### ISSUE TITLE
"Reply without jumping to reply box" function no longer works in Mac OS

### ISSUE THREAD

**Issue by Meta-Four** [knighty/fimfiction-issues#83]
The mouseover instructions on the reply button say "Hold ctrl to avoid jumping to reply box". In Mac OS, ctrl+clicking does exactly the same thing as right-clicking. If I ctrl+click or right-click on the reply button, I just get the broswer's generic drop-down menu, and the reply button does nothing.

I get the same results in Google Chrome v 58.0.3029.110 and Safari v 10.1.1. I'm running Mac OS X 10.10.5, if that matters.

On the previous version, where that function was triggered by shift+clicking, I never had any issues with the function.

**Comment by baxil** [comment]
Confirming in Mac OS X 10.11.6 (both Safari 10.1 and Firefox 53).  Control-clicking is intercepted by the OS for a context menu.  Shift-clicking used to have the expected avoid-jump functionality but now does not.  Option-clicking and command-clicking also jump.

**Comment by knighty** [comment]
Added shift key support
