### ISSUE TITLE
In 'Recent Group Threads' the name of the group is not displayed.

### ISSUE THREAD

**Issue by ocalhoun6** [knighty/fimfiction-issues#84]
In 'Recent Group Threads' (www.fimfiction.net/groups/threads), nowhere is the name of the group displayed in the list of threads. There's a group icon, but that may not be enough for groups that don't have an icon or for groups that frequently change their icon.

**Comment by knighty** [comment]
I don't really think this is an issue worth fixing. Doing so would require adding a lot of extra fluff to show the group name.
