### ISSUE TITLE
External resources cause problems with ePub export

### ISSUE THREAD

**Issue by Karkachu** [knighty/fimfiction-issues#86]
Hi! 

I'd like to file a notice on a problem a reader recently encountered with reading the ePub of [my story](https://www.fimfiction.net/story/240255/the-enchanted-library). It seems as though the text is missing? 

This was their original message: "Well, it has chapters, but the text is ah...AWOL. doesnt show up at all for some reason. It may just be the sweeping changes that got implemented, broke lots of things i guess. Anyways, it shows the chapters and their headers but the actual story text is gone and turning pages just jumps from chapter to chapter. "

And[ here is a screenshot](https://image.prntscr.com/image/EhebqXgMTuO5RQ1o2ncg9Q.png) of what appears on my epub reader (iBooks for Mac) when I downloaded it myself.

Thank you so much for all your hard work and help, and let me know please if I can help,

Monochromatic

![screen shot 2017-06-10 at 9 58 16 pm](https://user-images.githubusercontent.com/29349142/27008543-7e344f02-4e29-11e7-829c-6c3b4792a820.png)

**Comment by xaquseg** [comment]
Images need to output a simpler version of the code, and embeds probably need to be converted to a link to the resource. We should probably investigate using an iframe w/fallback as well in the embed case.

**Comment by knighty** [comment]
This should hopefully be fixed now. Can you let us know?
