### ISSUE TITLE
Links for unpublished stories with a password returns code 404

### ISSUE THREAD

**Issue by Huk256** [knighty/fimfiction-issues#89]
**OS:** Windos 10 (but probably, doesn't matter in that case) 
**Browser:** Any (tested on Chrome, Firefox, Edge)

**Way to reproduce:** 
1. Create a new story - set some password in the 'Unpublished View Password' textbox
2. Add a chapter and save
3. Copy the link to either the story root or the chapter and paste it in a browser, while logged out

**Expected behavior:**
1. User is prompted for the password set in the 'Unpublished View Password' text box
2. After entering the password, he can view the unpublished story

**Current behavior:**
The '404 - Page Not Found' error

**Example:**
https://www.fimfiction.net/story/376110/temp2

**Comment by knighty** [comment]
Currently an account is required to view unpublished stories

**Comment by Huk256** [comment]
I see... this must have changed after the update. If that's how it's supposed to work, then I guess this issue can be closed.

**Comment by Gyramuur** [comment]
Is this a permanent thing?
