### ISSUE TITLE
Page elements which open sub-menus should not also be links

### ISSUE THREAD

**Issue by baxil** [knighty/fimfiction-issues#96]
On the non-mobile site, the user menu at the top of your page has a "Stories" sub-menu which is BOTH a submenu activator AND a link.  Clicking the word "Stories" takes you to https://www.fimfiction.net/manage/stories, _even though_ hovering over that menu item pops a sub-menu out.  Similarly, clicking "Blog" takes you https://www.fimfiction.net/manage/blog-posts, and clicking any of the bookshelves in your Library takes you to the unread chapters of that bookshelf.  There is no other clickable link anywhere else in the site which takes you to those pages, and [users are missing the fact that those links exist](https://www.fimfiction.net/blog/741748/welp#comment/4568136).

**Expected behavior:** In Windows applications, clicking the anchor of a submenu toggles the submenu visibility (or closes the menu) without triggering any actions.  In Macintosh applications, clicking the anchor of a submenu is a null click.  In almost all web apps, clicking the anchor of a submenu is also a null action (e.g. going to the amazon.com front page and hovering over Departments, then hovering over one of the department sub-menu anchors, then trying to click the anchor, does nothing).  The current design breaks a nearly universal menu design principle.

**Requested Resolution:** Remove the links from the submenu anchors so that the words "Stories"/"Blog"/"(Bookshelf Name)" do nothing, and add the links as new menu items at the top of the corresponding submenu: e.g. "[Manage Stories](https://www.fimfiction.net/manage/stories)".

I would also recommend following the same principle with your top-level menus: anything which triggers the opening of a menu focuses the user's attention on the included items, not on the menu title.

**Comment by knighty** [comment]
Added those redundant links.
